# Generated by Django 1.10.4 on 2018-02-08 05:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctirsauthuser',
            name='stip_user',
        ),
        migrations.AddField(
            model_name='stipuser',
            name='api_key',
            field=models.CharField(default=b'', max_length=128),
        ),
        migrations.DeleteModel(
            name='CtirsAuthUser',
        ),
    ]
