# Generated by Django 1.10.4 on 2018-10-03 07:33


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0002_auto_20180208_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipuser',
            name='timezone',
            field=models.CharField(default=b'UTC', max_length=128),
        ),
    ]
