# Generated by Django 1.10.4 on 2019-01-10 04:18


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0003_stipuser_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='http_proxy',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='system',
            name='https_proxy',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
