# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-12 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0006_auto_20190208_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=10240)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_upload_stix_dir', models.CharField(default=b'', max_length=100)),
                ('path_sharing_policy_specifications', models.CharField(default=b'', max_length=100)),
                ('path_bootstrap_css_dir', models.CharField(default=b'', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CtirsConfig',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ctirs.GVAuthUser')),
                ('ctirs_host', models.CharField(default=b'https://localhost:10001', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Taxii',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('address', models.CharField(default=b'localhost', max_length=100)),
                ('port', models.IntegerField(default=80)),
                ('ssl', models.BooleanField(default=False)),
                ('path', models.CharField(default=b'/taxii-data', max_length=100)),
                ('collection', models.CharField(default=b'Default', max_length=100)),
                ('login_id', models.CharField(default=b'login_id', max_length=100)),
                ('login_password', models.CharField(default=b'login_password', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='default_taxii',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.SET_DEFAULT, to='ctirs.Taxii'),
        ),
        migrations.AddField(
            model_name='aliases',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ctirs.GVAuthUser'),
        ),
    ]
