# Generated by Django 1.10.4 on 2019-02-14 08:06


from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0010_auto_20190214_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='sharing_people',
            field=models.ManyToManyField(related_name='feed_sharing_people', to=settings.AUTH_USER_MODEL),
        ),
    ]
