# Generated by Django 1.10.4 on 2019-02-20 00:38


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0012_auto_20190215_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctirsconfig',
            name='user',
        ),
        migrations.AddField(
            model_name='config',
            name='ctirs_host',
            field=models.CharField(default=b'https://localhost:10001', max_length=100),
        ),
        migrations.DeleteModel(
            name='CtirsConfig',
        ),
    ]
