# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-20 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0014_auto_20190220_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipuser',
            name='administraive_area',
            field=models.TextField(default=None, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='stipuser',
            name='administraive_code',
            field=models.TextField(default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='stipuser',
            name='country_code',
            field=models.TextField(default=None, max_length=8, null=True),
        ),
    ]
