# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-20 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0015_auto_20190220_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='administraive_code',
            field=models.TextField(default=None, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='country_code',
            field=models.TextField(default=None, max_length=8, null=True),
        ),
    ]
