# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-02-20 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0016_auto_20190220_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stipuser',
            old_name='administraive_area',
            new_name='administrative_area',
        ),
        migrations.RenameField(
            model_name='stipuser',
            old_name='administraive_code',
            new_name='administrative_code',
        ),
    ]
