# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-03-01 00:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0020_auto_20190301_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNSConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_cti_extractor_threat_actors_list', models.TextField(default=b'', max_length=10240)),
                ('common_cti_extractor_white_list', models.TextField(default=b'', max_length=10240)),
                ('sns_identity_name', models.TextField(default=b's-tip-sns', max_length=32)),
                ('sns_header_title', models.TextField(default=b'S-TIP', max_length=32)),
                ('sns_body_color', models.TextField(default=b'#FFFFFF', max_length=32)),
                ('sns_version_path', models.TextField(default=b'/opt/s-tip/sns/version', max_length=1024)),
                ('sns_public_suffix_list_file_path', models.TextField(default=b'/opt/s-tip/rs/conf/public_suffix_list.dat', max_length=1024)),
                ('circl_mongo_host', models.TextField(default=b'localhost', max_length=128)),
                ('circl_mongo_port', models.IntegerField(default=27017)),
                ('circl_mongo_database', models.TextField(default=b'circl', max_length=64)),
                ('cs_custid', models.TextField(default=b'', max_length=64)),
                ('cs_custkey', models.TextField(default=b'', max_length=64)),
                ('rs_community_name', models.TextField(default=b'', max_length=64)),
                ('proxy_http', models.TextField(default=b'', max_length=128)),
                ('proxy_https', models.TextField(default=b'', max_length=128)),
                ('gv_l2_url', models.TextField(default=b'', max_length=128)),
                ('jira_host', models.TextField(default=b'', max_length=128)),
                ('jira_username', models.TextField(default=b'', max_length=64)),
                ('jira_password', models.TextField(default=b'', max_length=64)),
                ('jira_project', models.TextField(default=b'', max_length=64)),
                ('jira_type', models.TextField(default=b'', max_length=64)),
                ('smtp_port', models.IntegerField(default=25)),
                ('smtp_accept_mail_address', models.TextField(default=b'', max_length=128)),
            ],
            options={
                'db_table': 'stip_sns_system',
            },
        ),
    ]
