# Generated by Django 1.10.4 on 2019-03-01 04:17


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0021_snsconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsconfig',
            name='stix_ns_name',
            field=models.TextField(default=b's-tip', max_length=128),
        ),
        migrations.AddField(
            model_name='snsconfig',
            name='stix_ns_url',
            field=models.TextField(default=b'http://fsi.fujitsu.com', max_length=128),
        ),
        migrations.AlterField(
            model_name='group',
            name='locale',
            field=models.CharField(choices=[(b'en', 'English'), (b'pt-br', 'Portuguese'), (b'es', 'Spanish'), (b'ja', 'Japanese'), (b'fr', 'French'), (b'zh-cn', 'Chinese')], default='en', max_length=4),
        ),
    ]
