# Generated by Django 1.10.4 on 2019-03-01 04:31


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0022_auto_20190228_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsconfig',
            name='rs_host',
            field=models.TextField(default=b'https://localhost:10001/', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='rs_community_name',
            field=models.TextField(default=b'Default Community', max_length=64),
        ),
    ]
