# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-13 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0027_auto_20190417_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='snsconfig',
            name='slack_bot_channel',
            field=models.CharField(default=b'#s-tip', max_length=128),
        ),
        migrations.AddField(
            model_name='snsconfig',
            name='slack_bot_token',
            field=models.CharField(default=b'', max_length=128),
        ),
    ]
