# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2019-05-29 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0028_auto_20190514_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='stix2_package_id',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='locale',
            field=models.CharField(choices=[(b'en', 'English'), (b'pt-br', 'Portuguese'), (b'es', 'Spanish'), (b'ja', 'Japanese'), (b'fr', 'French'), (b'zh-cn', 'Chinese')], default='en', max_length=4),
        ),
    ]
