# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-07 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0031_auto_20190807_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phantom_auth_token',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='phantom_host',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='phantom_playbook_name',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='phantom_source_name',
            field=models.TextField(default='local', max_length=128),
        ),
    ]
