# Generated by Django 1.11.22 on 2019-08-20 00:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0032_auto_20190808_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='splunk_host',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='splunk_password',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='splunk_port',
            field=models.IntegerField(default=8089),
        ),
        migrations.AddField(
            model_name='profile',
            name='splunk_scheme',
            field=models.TextField(choices=[('http', 'http'), ('https', 'https')], default='https', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='splunk_username',
            field=models.TextField(default='', max_length=128),
        ),
    ]
