# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0033_auto_20190820_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='splunk_query',
            field=models.TextField(default='', max_length=10240),
        ),
    ]
