# Generated by Django 1.11.22 on 2019-08-20 07:21


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0034_profile_splunk_query'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='splunk_port',
            new_name='splunk_api_port',
        ),
        migrations.AddField(
            model_name='profile',
            name='splunk_web_port',
            field=models.IntegerField(default=8000),
        ),
    ]
