# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-12-13 02:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0035_auto_20190820_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='ctirs_host',
            field=models.CharField(default='https://localhost:10001', max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='default_taxii',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='ctirs.Taxii'),
        ),
        migrations.AlterField(
            model_name='config',
            name='path_bootstrap_css_dir',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='path_sharing_policy_specifications',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='config',
            name='path_upload_stix_dir',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='feed',
            name='sharing_range_type',
            field=models.CharField(choices=[('all', 'With the CSC Community'), ('group', 'With a group'), ('people', 'With people')], default='all', max_length=10),
        ),
        migrations.AlterField(
            model_name='feed',
            name='tlp',
            field=models.CharField(choices=[('RED', 'RED'), ('AMBER', 'AMBER'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default='AMBER', max_length=10),
        ),
        migrations.AlterField(
            model_name='gvauthuser',
            name='css_thema',
            field=models.CharField(default='default', max_length=30),
        ),
        migrations.AlterField(
            model_name='mongoconfig',
            name='db',
            field=models.CharField(default='ctirs', max_length=100),
        ),
        migrations.AlterField(
            model_name='mongoconfig',
            name='host',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='attck_mongo_database',
            field=models.TextField(default='attck', max_length=64),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='attck_mongo_host',
            field=models.TextField(default='localhost', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='circl_mongo_database',
            field=models.TextField(default='circl', max_length=64),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='circl_mongo_host',
            field=models.TextField(default='localhost', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='common_cti_extractor_threat_actors_list',
            field=models.TextField(default='', max_length=10240),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='common_cti_extractor_white_list',
            field=models.TextField(default='', max_length=10240),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='cs_custid',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='cs_custkey',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='gv_l2_url',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='jira_host',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='jira_password',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='jira_project',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='jira_type',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='jira_username',
            field=models.TextField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='phantom_auth_token',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='phantom_host',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='phantom_playbook_name',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='phantom_source_name',
            field=models.TextField(default='local', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='proxy_http',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='proxy_https',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='rs_community_name',
            field=models.TextField(default='Default Community', max_length=64),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='rs_host',
            field=models.TextField(default='https://localhost:10001/', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='slack_bot_channel',
            field=models.CharField(default='#s-tip', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='slack_bot_token',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='smtp_accept_mail_address',
            field=models.TextField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='sns_body_color',
            field=models.TextField(default='#FFFFFF', max_length=32),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='sns_header_title',
            field=models.TextField(default='S-TIP', max_length=32),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='sns_identity_name',
            field=models.TextField(default='s-tip-sns', max_length=32),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='sns_public_suffix_list_file_path',
            field=models.TextField(default='/opt/s-tip/rs/data/public_suffix_list.dat', max_length=1024),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='sns_version_path',
            field=models.TextField(default='/opt/s-tip/sns/version', max_length=1024),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='stix_ns_name',
            field=models.TextField(default='s-tip', max_length=128),
        ),
        migrations.AlterField(
            model_name='snsconfig',
            name='stix_ns_url',
            field=models.TextField(default='http://fsi.fujitsu.com', max_length=128),
        ),
        migrations.AlterField(
            model_name='stipuser',
            name='api_key',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='stipuser',
            name='ci',
            field=models.CharField(choices=[('Information and Communication Services', 'CI_Information and Communication Services'), ('Financial Services', 'CI_Financial Services'), ('Aviation Services', 'CI_Aviation Services'), ('Railway Services', 'CI_Railway Services'), ('Electric Power Supply Services', 'CI_Electric Power Supply Services'), ('Gas Supply Services', 'CI_Gas Supply Services'), ('Government and Administrative Services (Including Municipal Government)', 'CI_Government and Administrative Services (Including Municipal Government)'), ('Medical Services', 'CI_Medical Services'), ('Water Services', 'CI_Water Services'), ('Logistics Services', 'CI_Logistics Services'), ('Chemical Industries', 'CI_Chemical Industries'), ('Credit Card Services', 'CI_Credit Card Services'), ('Petroleum Industries', 'CI_Petroleum Industries'), ('Other', 'CI_Other')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stipuser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('ja', 'Japanese'), ('fr', 'French'), ('zh-cn', 'Chinese')], default='en', max_length=4),
        ),
        migrations.AlterField(
            model_name='stipuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ROLE_CHOICE_admin'), ('user', 'ROLE_CHOICE_user'), ('machine', 'ROLE_CHOICE_machine'), ('machine_feed_only', 'ROLE_CHOICE_machine_feed_only'), ('machine_bot', 'ROLE_CHOICE_machine_bot')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='stipuser',
            name='screen_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='stipuser',
            name='sector',
            field=models.CharField(choices=[('chemical', 'SECTOR_GROUP_Chemical Sector'), ('commercial', 'SECTOR_GROUP_Commercial Facilities Sector'), ('communication', 'SECTOR_GROUP_Communications Sector'), ('critical', 'SECTOR_GROUP_Critical Manufacturing Sector'), ('dams', 'SECTOR_GROUP_Dams Sector'), ('defense', 'SECTOR_GROUP_Defense Industrial Base Sector'), ('emergency', 'SECTOR_GROUP_Emergency Services Sector'), ('energy', 'SECTOR_GROUP_Energy Sector'), ('financial', 'SECTOR_GROUP_Financial Services Sector'), ('food', 'SECTOR_GROUP_Food and Agriculture Sector'), ('government', 'SECTOR_GROUP_Government Facilities Sector'), ('healthcare', 'SECTOR_GROUP_Healthcare and Public Health Sector'), ('information', 'SECTOR_GROUP_Information Technology Sector'), ('nuclear', 'SECTOR_GROUP_Nuclear Reactors, Materials, and Waste Sector'), ('other', 'SECTOR_GROUP_Other'), ('transport', 'SECTOR_GROUP_Transportation Systems Sector'), ('water', 'SECTOR_GROUP_Water and Wastewater Systems Sector')], max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='stipuser',
            name='timezone',
            field=models.CharField(default='UTC', max_length=128),
        ),
        migrations.AlterField(
            model_name='stipuser',
            name='tlp',
            field=models.CharField(choices=[('RED', 'RED'), ('AMBER', 'AMBER'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE')], default='AMBER', max_length=10),
        ),
        migrations.AlterField(
            model_name='system',
            name='http_proxy',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='system',
            name='https_proxy',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='system',
            name='public_suffix_list_file_path',
            field=models.FilePathField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='taxii',
            name='address',
            field=models.CharField(default='localhost', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxii',
            name='collection',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxii',
            name='login_id',
            field=models.CharField(default='login_id', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxii',
            name='login_password',
            field=models.CharField(default='login_password', max_length=100),
        ),
        migrations.AlterField(
            model_name='taxii',
            name='path',
            field=models.CharField(default='/taxii-data', max_length=100),
        ),
    ]
