# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-04-08 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0036_auto_20191213_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='stix_version',
            field=models.CharField(default='1.2', max_length=8, null=True),
        ),
    ]
