# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-15 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0038_auto_20200630_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipuser',
            name='country_code',
            field=models.TextField(default='US', max_length=8, null=True),
        ),
    ]
