# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-26 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0040_stipuser_totp_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='post_org',
            field=models.TextField(default='', max_length=1024),
        ),
    ]
