# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0040_stipuser_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipuser',
            name='totp_secret',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
