# Generated by Django 3.2.4 on 2021-06-23 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0041_feed_post_org'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('pt-br', 'Portuguese'), ('es', 'Spanish'), ('ja', 'Japanese'), ('fr', 'French'), ('zh-cn', 'Chinese')], default='en', max_length=16),
        ),
        migrations.AlterField(
            model_name='stipuser',
            name='role',
            field=models.CharField(choices=[('admin', 'ROLE_CHOICE_admin'), ('user', 'ROLE_CHOICE_user'), ('machine', 'ROLE_CHOICE_machine'), ('machine_feed_only', 'ROLE_CHOICE_machine_feed_only'), ('machine_bot', 'ROLE_CHOICE_machine_bot')], default='user', max_length=32),
        ),
    ]
