# Generated by Django 3.2.4 on 2022-02-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0043_alter_feed_package_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipuser',
            name='confidence',
            field=models.IntegerField(default=50),
        ),
    ]
