# Generated by Django 3.2.4 on 2022-03-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0045_feed_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='stipuser',
            name='identity_id',
            field=models.CharField(default='', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='stipuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
