# Generated by Django 3.2.4 on 2022-04-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0046_auto_20220308_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sns_filter',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
