# Generated by Django 3.2.4 on 2022-04-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0047_profile_sns_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='opinion',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
