# Generated by Django 3.2.4 on 2022-08-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctirs', '0048_notification_opinion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stipuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
